version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: lis
      POSTGRES_USER: lis
      POSTGRES_PASSWORD: lis
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lis -d lis"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: lis
      POSTGRES_PASSWORD: lis
      POSTGRES_DB: lis
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: pnpm start

volumes:
  postgres-data:
