export const DEFAULT_TEXT_INPUT_MAX_LENGTH = 512;
export const DEFAULT_TEXTAREA_MAX_LENGTH = 2000;

export const PATHOGEN_NAME_MAX_LENGTH = 255;
export const PATHOGEN_CLINICAL_SIGNIFICANCE_MAX_LENGTH = 500;
